import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NextNavbarSimple from "../components/NavbarSimple";
import { useEffect, useState } from "react";
import axios from "axios";
import Footer from "../components/Footer";
import router from "next/router";
import CartForm from "../components/CartForm";

export default function Home() {
  const [user, setUser] = useState(null);
  const [order, setOrder] = useState(null);

  useEffect(async () => {
    // LINK Prepare credentials for axios
    const config = {
      headers: {
        "Content-Type": "application/json",
      },
    };

    const simple_config = {
      headers: {
        "Content-Type": "application/json",
      },
    };

    const token = window.localStorage.getItem("token");

    const order_id = window.localStorage.getItem("order_id");

    var result = -1;

    if (token != null && token != undefined) {
      config.headers["authorization"] = `Token ${token}`;
      axios.defaults.headers.common["Authorization"];

      await getUser(config, setUser);

      result = await getOrder(config, order_id, setOrder);
    } else {
      getOrder(simple_config, order_id, setOrder);
    }

    if (result == -1) {
      getOrder(simple_config, order_id, setOrder);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Technology Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextNavbarSimple user={user} login={false}/>

      <main className={styles.main}>
        <CartForm order={order} user={user}/>
      </main>

      <Footer />
    </div>
  );
}

const getOrder = async (config, order_id, setOrder) => {
  const products_url = `http://127.0.0.1:8000/store/cart/${order_id}/`;

  axios
    .get(products_url, config)
    .then(async (res) => {
      const result = await res.data["Result"];
      if (result == "Error") {
        return -1;
      } else {
        await setOrder(result);
        return 1;
      }
    })
    .catch((error) => {
      console.log(error);
      return -1;
    });
};

const getUser = async (config, setUser) => {
  const auth_user = "http://127.0.0.1:8000/customer-account/check-auth/";
  axios
    .get(auth_user, config)
    .then(async (res) => {
      const result = await res.data;
      setUser(result);
    })
    .catch((error) => {
      console.log(error);
    });
};
