import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NextNavbar from "../components/Navbar";
import { useEffect, useState } from 'react';

export default function Home() {

  const [user, setUser] = useState(null)

  useEffect(() => {setUser(null)}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Technology Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextNavbar
        user={user == null ? null : user}
      />

      <main className={styles.main}>
        <div className={styles.container}>
          
        </div>
        
      </main>

      {/* Here goes the Footer */}
    </div>
  )
}
