import Head from "next/head";
import Image from "next/image";
import styles from "../../../../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import Footer from "../../../../components/Footer";
import NextNavbarSimple from "../../../../components/NavbarSimple";
import router from "next/router";
import { useRouter } from "next/router";
import EditAddressForm from '../../../../components/EditAddressForm'

export default function CreateAddress() {
  const [user, setUser] = useState(null);
  const router = useRouter();
  const { id } = router.query;
  const [user_id, setUser_id] = useState(null);

  useEffect(() => {
    var temp_id;
    if (id != undefined && id != null) {
      window.localStorage.setItem("user_id", id);
      temp_id = id;
      setUser_id(temp_id);
    } else {
      temp_id = window.localStorage.getItem("user_id");
      setUser_id(temp_id);
    }

    getUser(setUser);
  }, []);

  const createAddressHandler = async (body) => {
    createAddress(body);
  };

  return user == null?(
    <div></div>
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Technology Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NextNavbarSimple user={user == null ? null : user} login={true} />

      <main className={styles.main}>
        <EditAddressForm
          user={user}
          address={null}
          updateAddress={null}
          createAddress={createAddressHandler}
          deleteAddress={null}
        />
      </main>
      <Footer />
    </div>
  );
}

// LINK get User
const getUser = (setUser) => {
  const config = {
    headers: {
      "Content-Type": "application/json",
    },
  };

  const token = window.localStorage.getItem("token");

  config.headers["authorization"] = `Token ${token}`;
  axios.defaults.headers.common["Authorization"];

  const auth_user = "http://127.0.0.1:8000/customer-account/check-auth/";
  axios
    .get(auth_user, config)
    .then((res) => {
      const result = res.data;
      setUser(result);
      return;
    })
    .catch((error) => {
      console.log(error);
    });
};

// LINK update Address
const createAddress = async (body, setAddress) => {
  const config = {
    headers: {
      "Content-Type": "application/json",
    },
  };

  const token = window.localStorage.getItem("token");

  config.headers["authorization"] = `Token ${token}`;
  axios.defaults.headers.common["Authorization"];

  const address_url = `http://127.0.0.1:8000/customer-account/manage-address/create/`;
  axios
    .post(address_url, body, config)
    .then(async (res) => {
      const result = await res.data;
      return;
    })
    .catch((error) => {
      console.log(error);
    });
};
